rvm:
  - 1.8.7
  - 1.9.3
  - 2.2.0
script: 'bundle exec rake'
env:
  - PUPPET_VERSION=3.8.6
  - PUPPET_VERSION=4.4.1
matrix:
  exclude:
    # No support for Ruby 2.0 before Puppet 3.2
    - rvm: 2.2.0
      env: PUPPET_VERSION=3.8.6
    - rvm: 1.8.7
      env: PUPPET_VERSION=4.4.1

